### ISSUE TITLE
Link Python-RPN Mailing List Message in Code Comment

### ISSUE THREAD

**Issue by jeixav** [neishm/fstd2nc#1]
https://github.com/neishm/fstd2nc/blob/072e1505aef6661e94ac33abf8d80083ce15db6c/fstd2nc.py#L74

That line references an example I prepared. I suggest a reference be added to: http://internallists.cmc.ec.gc.ca/pipermail/python-rpn/2015-February/000010.html. It gives details on how I came to use of `rmn.fstlir(..., dtype=np.float32)`.

Note the same method used in the following example: https://wiki.cmc.ec.gc.ca/wiki/Python-RPN/2.0/examples#Example_4:_Plot_RPN_STD_field_on_an_X-grid.

**Comment by neishm** [comment]
Thanks for the links!  Good to know this is a common workaround for this type of data.  Added to the comments.
