### ISSUE TITLE
Move "leadtime" and "reftime" out of the coordinates list

### ISSUE THREAD

**Issue by neishm** [neishm/fstd2nc#27]
Some netCDF utilities complain about these variables when they're in the list of coordinates.  This may result in the lat/lon coordinates not getting properly utilized, or annoying warning messages in stdout.  The [CF Metadata Conventions](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html#coordinate-system) seems to indicate that these things *should* go in the coordinates, but I guess in practice that's not done?

One alternative may be to list the leadtime / reftime as [`ancillary_variables`](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html#ancillary-data) in the time axis, since they provide information related to time.

**Comment by neishm** [comment]
One workaround for the time being is to add the following to the command-line converter: `--exclude=leadtime,reftime`

**Comment by deacud** [comment]
Hi Mike. I had similar experiences in the past with tools that were unable to follow the CF conventions. 

I am no longer up-to-date with the proper usage of 'leadtime' and 'reftime', but they look OK to me, based on what I see in the metadata of an nc file generated by the converter a few months ago.

Here is another example of usage which is similar to that implemented in the converter:

https://confluence.ecmwf.int/display/COPSRV/Guide+to+NetCDF+encoding+for+C3S+providers

**Comment by neishm** [comment]
Thanks for the link, @deacud.  Sounds like the converter's doing the right thing.  Maybe it's better to leave things as-is, and not risk breaking something.  If any instances come up where this is a critical issue with a netCDF viewer, maybe it can be revisited.

**Comment by deacud** [comment]
I think it is important for the nc files not to cause major problems when viewed with the most commonly used netcdf viewers, such as Panoply and IDV. For the less common viewers/tools, the user could be advised that just manipulating the metadata could solve the problem. I had experiences when the removal of the Conventions global attribute was sufficient. Not finding the attribute, the tool did not try to follow any convention and bypassed the interpretation of the less known features following a basic reading approach instead.

**Comment by neishm** [comment]
@deacud what problems in particular did you encounter with the coordinates?  I just tried the latest Panoply (4.11.6) and IDV (5.7) on some test files, and it had no problem with leadtime and reftime in the coordinates.  Ncview complains, but still seems to draw a map overlay anyway.  Maybe I need to try other grid projections or time axes...

**Comment by deacud** [comment]
I had no problems with either Panoply or IDV and only remember issues that others reported when they tried to read NetCDF files that I created following the CF conventions. (That was before I started to use your converter.) The NetCDF drivers of some libraries/tools, such as GDAL, were unable to fully/properly interpret the metadata compliant with the CF conventions. Some of them may still be unable to read the projection information. In that case they will look for the actual latitude and longitude coordinates. So, having these coordinates in the nc files will help in such circumstances.

I would say that the converter does a very good job if the metadata of the netcdf files generated by it can be fully interpreted by Panoply and IDV. NCL could be as good as these tools at keeping up with the new versions of the CF conventions. GDAL might also have become better in the meantime.

You cannot make everyone happy. Adding some info to the wiki page regarding possible issues with readers that are not fully "compliant" with CF conventions, especially with their most recent versions, might help. Tips, such as the manipulation of the metadata, including the removal of the "Conventions" attribute, should help.




https://gdal.org/drivers/vector/netcdf.html

**Comment by deacud** [comment]
The link above is not the one I intended to include. This is the right one:

https://gdal.org/drivers/raster/netcdf.html

"•Improved support for CF-1.5 projected and geographic SRS reading and writing"

That seems to indicate that not all projections are readable yet in GDAL.

**Comment by neishm** [comment]
Having some explicit examples would be help address this kind of problem.  E.g., "converting file X using options Y causes problems with netCDF tool Z".  I have an assortment of sample FST files on ppp4 that are used to test netCDF conversion, I will try using a bunch of viewers on the converted files and see what happens...

**Comment by neishm** [comment]
There was a GDAL issue that came up recently in regards to the converted netCDF files.
https://gccode.ssc-spc.gc.ca/ec-msc/msc-geomet/-/issues/59 (internal link).

The grid orientation was being transposed in some versions of GDAL.  The solution was to upgrade PROJ to at least version 7.0.1 when utilizing these files.

**Comment by neishm** [comment]
In the recent versions of fstd2nc, there's now a command-line option `--no-conventions` for cases where some tools can't recognize the conventions (to streamline workaround in https://github.com/neishm/fstd2nc/issues/27#issuecomment-715927999).

**Comment by deacud** [comment]
Hi Mike. This should be very useful in those cases. Is its effect the removal of the 'Conventions' global attribute?

**Comment by neishm** [comment]
Yep, that's exactly what it does!

**Comment by deacud** [comment]
Removing that attribute was sufficient in my experience with tools that had trouble interpreting CF-compliant metadata. No 'Convention' attribute, no attempt to interpret the metadata.

**Comment by neishm** [comment]
Is that sufficient for addressing this issue? Maybe I could add a comment in the `--help` for `--no-conventions` to mention how it could be useful in this circumstance...

**Comment by deacud** [comment]
It should be sufficient, at least in some cases. I remember seeing the slice of code of a particular tool/library (GDAL?) with conditional branching based on the existence of the 'Conventions' global attribute in the netcdf file.

**Comment by deacud** [comment]
I also think that adding a comment in the 'help' info for that option, as you suggested, would be very useful.
