### ISSUE TITLE
Can't remove diagnostic level

### ISSUE THREAD

**Issue by skhicks** [neishm/fstd2nc#30]
I'm trying to remove the diagnostic levels from my temperature and humidity profiles using the "--ignore-diag-level" option, but it doesn't seem to be working. I still get two temperature variables in my final .nc file as TT_vgrid4 and TT_vgrid5. 

I have a standard RPN std file that I use as input (2019060106_000_domgrid). It has been interpolated to several lat/lon gridpoints before conversion using pgsm. 

This is the command I run: 
fstd2nc --profile-thermodynamic-vars=HU,TT,GZ,PX,WW --thermodynamic-levels --keep-LA-LO --ignore-diag-level --opdict 2019060106_000_domgrid 2019060106_000_domgrid2.nc

Output: 
Found 1 RPN input file(s)
Warning: Mixture of model / height levels found.  This will cause multiple
    definitions of variables in the output.  If this is undesired, you
    could try using --ignore-diag-level or --diag-as-model-level.
Warning: Multiple level axes.  Appending integer suffixes to their names.
Warning: Multiple definitions of HU.  Adding unique suffixes vgrid4, vgrid5.
Warning: Multiple definitions of TT.  Adding unique suffixes vgrid4, vgrid5.

Even though I have the option to ignore the diagnostic level it still adds them. I have also tried "--diag-as-model-level" without success. Additionally, it seems to put PX, HU/TT, and GZ all on different level variables, despite them all being on thermodynamic levels. Why is this the case? 

Thanks for your assistance and Best Regards.

**Comment by neishm** [comment]
Thanks for filing the bug report.  This does seem like weird behaviour.  The `--thermodynamic-levels` option is clearly having no effect on the result.  This is a relatively new option, so it's possible there's a bug in the implementation.  Is your test file available on the science network somewhere?

**Comment by skhicks** [comment]
Thanks very much for getting back to me! 
My test file is here: 
/home/shh000/test_grid/2019060106_000_domgrid (this file has been interpolated onto specific lat/lon points using pgsm)

The output .nc file is: 
/home/shh000/test_grid/2019060106_000_domgrid2.nc

If you need anything else please let me know.

**Comment by neishm** [comment]
Looks like it's having trouble due to multiple "`!!`" records in the RPN std file.  None of those records have an IP1/IP2/IP3 that matches the IG1/IG2/IG3 from the fields, so the converter doesn't know which one to use for defining diagnostic level and thermodynamic levels.  So it just ignores those options entirely.  If I force the file to have only one "`!!`" record with consistent keys:
```
editfst -s 2019060106_000_domgrid -d 2019060106_000_domgrid2 -e <<EOF
exclure(-1,'!!')
stdcopi(-1)
desire(-1,'!!')
zap(-1,-1,-1,-1,1,2,3)
stdcopi(-1)
EOF
```
Then I can use the `--theromodynamic-levels` and `--ignore-diag-level` options:
```
fstd2nc 2019060106_000_domgrid2 2019060106_000_domgrid2.nc --thermodynamic-levels --ignore-diag-level --opdict
```
This gets rid of the annoying _vgrid4 and _vgrid5 partitionings.  However, there are still two sets of levels because `WW` is missing the bottom model level (0.997497) in the RPN std file.
```
netcdf \2019060106_000_domgrid2 {
dimensions:
        time = UNLIMITED ; // (1 currently)
        level1 = 62 ;
        i = 251 ;
        level2 = 61 ;
variables:
        float GZ(time, level1, i) ;
                GZ:_FillValue = 1.e+30f ;
                GZ:coordinates = "leadtime reftime lon lat" ;
                GZ:long_name = "Geopotential height" ;
                GZ:units = "dam" ;
        double time(time) ;
                time:standard_name = "time" ;
                time:long_name = "Validity time" ;
                time:axis = "T" ;
                time:units = "hours since 2019-06-01 06:00:00" ;
                time:calendar = "gregorian" ;
        float level1(level1) ;
                level1:axis = "Z" ;
                level1:positive = "down" ;
                level1:standard_name = "atmosphere_hybrid_sigma_ln_pressure_coordinate" ;
                level1:formula = "p = exp(a+b*log(ps/pref))" ;
                level1:formula_terms = "a: a_1 b: b_1 ps: P0 pref: pref" ;
                level1:coordinates = "a_1 b_1" ;
        double a_1(level1) ;
        double b_1(level1) ;
        double pref ;
                pref:units = "Pa" ;
        float leadtime(time) ;
                leadtime:standard_name = "forecast_period" ;
                leadtime:long_name = "Lead time (since forecast_reference_time)" ;
                leadtime:units = "hours" ;
        double reftime ;
                reftime:standard_name = "forecast_reference_time" ;
                reftime:units = "hours since 2019-06-01 06:00:00" ;
                reftime:calendar = "gregorian" ;
        float lon(i) ;
                lon:long_name = "longitude" ;
                lon:standard_name = "longitude" ;
                lon:units = "degrees_east" ;
        float lat(i) ;
                lat:long_name = "latitude" ;
                lat:standard_name = "latitude" ;
                lat:units = "degrees_north" ;
        float HU(time, level1, i) ;
                HU:_FillValue = 1.e+30f ;
                HU:coordinates = "leadtime reftime lon lat" ;
                HU:long_name = "Specific humidity" ;
                HU:units = "kg/kg" ;
        float IH(time, i) ;
                IH:_FillValue = 1.e+30f ;
                IH:coordinates = "leadtime reftime lon lat" ;
                IH:long_name = "Water vapor vertical integration" ;
                string IH:units = "kg/m²?" ;
        float P0(time, i) ;
                P0:_FillValue = 1.e+30f ;
                P0:coordinates = "leadtime reftime lon lat" ;
                P0:long_name = "Surface pressure" ;
                P0:units = "mb" ;
        float PX(time, level1, i) ;
                PX:_FillValue = 1.e+30f ;
                PX:coordinates = "leadtime reftime lon lat" ;
                PX:long_name = "Hydrostatic pressure" ;
                PX:definition_opdict = "Hydrostatic pressure at each point for the field for the corresponding vertical level" ;
                PX:units = "hPa" ;
        float TT(time, level1, i) ;
                TT:_FillValue = 1.e+30f ;
                TT:coordinates = "leadtime reftime lon lat" ;
                TT:long_name = "Air temperature" ;
                string TT:units = "°?C" ;
        float WW(time, level2, i) ;
                WW:_FillValue = 1.e+30f ;
                WW:coordinates = "leadtime reftime lon lat" ;
                WW:long_name = "Vertical Motion" ;
                WW:units = "pa/s" ;
        float level2(level2) ;
                level2:axis = "Z" ;
                level2:positive = "down" ;
                level2:standard_name = "atmosphere_hybrid_sigma_ln_pressure_coordinate" ;
                level2:formula = "p = exp(a+b*log(ps/pref))" ;
                level2:formula_terms = "a: a_2 b: b_2 ps: P0 pref: pref" ;
                level2:coordinates = "a_2 b_2" ;
        double a_2(level2) ;
        double b_2(level2) ;

// global attributes:
                :Conventions = "CF-1.6" ;
                :history = "2021-05-27 23:47:13: /fs/ssm/eccc/crd/ccmr/EC-CAS/master/fstd2nc_0.20210305.0_all/bin/fstd2nc 2019060106_000_domgrid2 2019060106_000_domgrid2.nc --thermodynamic-levels --ignore-diag-level --opdict" ;
}
```

**Comment by neishm** [comment]
What I could do is add warnings for the `--thermodynamic-levels` and `--ignore-diag-level` options if it's having trouble identifying a suitable vertical coordinate record (or maybe just pick one at random when given multiple choices...)

**Comment by neishm** [comment]
Hi @skhicks, I've just added a new test version of fstd2nc on the science network which should address some of the problems:
```
. ssmuse-sh -p eccc/crd/ccmr/EC-CAS/master/fstd2nc_0.20210305.1-rc1
```
For your case, I think the command-line would look like
```
fstd2nc --thermodynamic-levels --ignore-diag-level --opdict 2019060106_000_domgrid 2019060106_000_domgrid2.nc
```
It will still give different vertical levels for `WW`, but that's because in the RPN std file that field is missing the lowest thermodynamic level.

Side note: the `--profile-thermodynamic-vars` controls something unrelated (for station profiles in RPN std files, which have a different structure).  Also, `--keep-LA-LO` should not be needed in this case ("lat" and "lon" axes are already decoded).

**Comment by skhicks** [comment]
Hi neishm, thanks for getting back to me and sorry for the late response. I was trying to find out why I'd have multiple !! levels. Presumably because GZ, HU/TT, and WW are all on different vertical coordinates? 

Thanks for the new version, I will test it to see what I get.

**Comment by skhicks** [comment]
@neishm I've tested the new version on a few of my files and the results look very nice. 
One question - what are the a_1,2 and b_1,2 fields in the .nc file? 
Thanks!

**Comment by neishm** [comment]
They're the A and B coefficients for determining the hydrostatic pressure at each model level.  There's a nice visual at https://wiki.cmc.ec.gc.ca/wiki/Vgrid#Vertical_coordinates_in_fst_files showing the formula.  If you have a log-hydrostatic coordinate, then that would correspond to the rightmost plot in that image.  It *should* result in the same pressure values as your `PX` field, if I understand things correctly.

**Comment by neishm** [comment]
Final version 0.20210305.1 is now released.  On science network it can be accessed by:
```
. ssmuse-sh -p eccc/crd/ccmr/EC-CAS/master/fstd2nc_0.20210305.1
```
@skhicks, is the issue with the diagnostic level resolved now?  Is it safe to close this issue?

**Comment by skhicks** [comment]
@neishm Thanks very much. Yes, we can consider the issue resolved now and safe to close. Thanks again for your help.

**Comment by neishm** [comment]
You're welcome!  Glad it's working!
