### ISSUE TITLE
Is there a way to control variable naming in case of multiple vertical axes

### ISSUE THREAD

**Issue by guziy** [neishm/fstd2nc#37]
I have an SSH field on rbitrary and on height above the sea vertical levels. So in the resulting netcdf file I get 2 fields:

```
   float zos_vgrid0(time, lat, lon) ;
            zos_vgrid0:_FillValue = 1.e+30f ;
            zos_vgrid0:nomvar = "SSH" ;
            zos_vgrid0:coordinates = "time lon lat" ;
            zos_vgrid0:long_name = "Sea surface height" ;
            zos_vgrid0:units = "m" ;
            zos_vgrid0:definition_opdict = "Sea surface height above a reference surface (e.g. geoid)" ;
            zos_vgrid0:grid_mapping = "crs_latlon" ;
            zos_vgrid0:missing_value = "1.e+30f" ;
            zos_vgrid0:stdscale = "1.f" ;
            zos_vgrid0:stdoffset = "0.f" ;
            zos_vgrid0:standard_name = "sea_surface_height_above_geoid" ;
    float zos_vgrid3(time, sfclevel, lat, lon) ;
            zos_vgrid3:_FillValue = 1.e+30f ;
            zos_vgrid3:nomvar = "SSH" ;
            zos_vgrid3:coordinates = "time lon lat" ;
            zos_vgrid3:long_name = "Sea surface height" ;
            zos_vgrid3:units = "m" ;
            zos_vgrid3:definition_opdict = "Sea surface height above a reference surface (e.g. geoid)" ;
            zos_vgrid3:grid_mapping = "crs_latlon" ;
            zos_vgrid3:missing_value = "1.e+30f" ;
            zos_vgrid3:stdscale = "1.f" ;
            zos_vgrid3:stdoffset = "0.f" ;
            zos_vgrid3:standard_name = "sea_surface_height_above_geoid" ;

```

I am curious if there is an option to change `zos_vgrid0` back to `zos`. I have the following in my `.ini` file.

```ini
[SSH]
rename: zos
units = m 
missing_value = 1.e+30f 
coordinates = time lon lat 
stdscale = 1.f 
stdoffset = 0.f
standard_name = sea_surface_height_above_geoid
```

If not, then I guess I could just use ncrename or other tools.

Thanks

**Comment by guziy** [comment]
Sorry for this noise, I was actually asked to remove the zos_vgrid3 from the netcdf completely, so if there is no such functionality, then ok, I can close this issue.

**Comment by neishm** [comment]
Hmm... doesn't look like the renaming works when the names were already modified for multiple vertical coordinates.  That functionality can be added, though.

In the mean time, your case where you want to remove the arbitrary levels entirely you could use `--filter 'kind!=3'`.

**Comment by guziy** [comment]
Thanks Michael,  I will use the filter option.

**Comment by guziy** [comment]
Hi:

me again))

Is it possible to achieve the following with the filter option?

```
--filter 'ip1 not in [59868832, 59968832]' 
```

I tried the above but get the following exception
<details><summary>Exception info</summary>
<p>

```bash
Will look for variables: ETAS SSH
Traceback (most recent call last):
  File "/fs/site4/eccc/cmd/e/olh001/maestro/cmde_postproc_prog/hub/work/20220210000000/main/cmde_postproc/datamart_netcdf/fst2cdf/bin/fstd2nc", line 11, in <module>
    load_entry_point('fstd2nc==0.20210305.1', 'console_scripts', 'fstd2nc')()
  File "/fs/ssm/eccc/crd/ccmr/EC-CAS/fstd2nc/0.20210305.1/all/lib/python/fstd2nc/__main__.py", line 107, in _fstd2nc_cmdline_trapped
    _fstd2nc_cmdline (*args, **kwargs)
  File "/fs/ssm/eccc/crd/ccmr/EC-CAS/fstd2nc/0.20210305.1/all/lib/python/fstd2nc/__main__.py", line 64, in _fstd2nc_cmdline
    buf = buffer_type(infiles, **args)
  File "/fs/ssm/eccc/crd/ccmr/EC-CAS/fstd2nc/0.20210305.1/all/lib/python/fstd2nc/__init__.py", line 65, in __init__
    super(Buffer,self).__init__(filename, *args,**kwargs)
  File "/fs/ssm/eccc/crd/ccmr/EC-CAS/fstd2nc/0.20210305.1/all/lib/python/fstd2nc/mixins/compat.py", line 48, in __init__
    super(FSTD_Compat,self).__init__(*args,**kwargs)
  File "/fs/ssm/eccc/crd/ccmr/EC-CAS/fstd2nc/0.20210305.1/all/lib/python/fstd2nc/mixins/netcdf.py", line 162, in __init__
    super(netCDF_IO,self).__init__(*args,**kwargs)
  File "/fs/ssm/eccc/crd/ccmr/EC-CAS/fstd2nc/0.20210305.1/all/lib/python/fstd2nc/mixins/netcdf.py", line 112, in __init__
    super(netCDF_Atts,self).__init__(*args,**kwargs)
  File "/fs/ssm/eccc/crd/ccmr/EC-CAS/fstd2nc/0.20210305.1/all/lib/python/fstd2nc/mixins/removestuff.py", line 49, in __init__
    super(RemoveStuff,self).__init__(*args,**kwargs)
  File "/fs/ssm/eccc/crd/ccmr/EC-CAS/fstd2nc/0.20210305.1/all/lib/python/fstd2nc/mixins/filter.py", line 52, in __init__
    flags &= self._do_filter(records, cmd)
  File "/fs/ssm/eccc/crd/ccmr/EC-CAS/fstd2nc/0.20210305.1/all/lib/python/fstd2nc/mixins/filter.py", line 60, in _do_filter
    return eval(cmd, None, p)
  File "<string>", line 1, in <module>
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

</p>
</details>

Thanks

**Comment by neishm** [comment]
The ip1 values are stored in an array, so it would require a different syntax:
```
--filter '(ip1!=59868832)&(ip1!=59968832)' 
```
The parentheses are necessary to get the right order of operations with the `&` operator.  Alternatively, you can chain the conditions together with multiple filters:
```
--filter 'ip1!=59868832 --filter 'ip1!=59968832' 
```

**Comment by guziy** [comment]
Thanks Michael:

in a numpy array, got it! so maybe this would work `~ìp1.isin([59868832, 59968832])`, I could test if not then your suggestion is fine as well.

**Comment by neishm** [comment]
Maybe it depends on the numpy version.  When I tried your approach with numpy 1.19.5 I get
```
AttributeError: 'numpy.ndarray' object has no attribute 'isin'
```

**Comment by guziy** [comment]
Yes, you are right I found this in numpy module did not check carefully, it is actually a module method not the ndarray one. My version was saying that my ip1 are actually a masked array not simple ndarray.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

**Comment by neishm** [comment]
It looks like the numpy module is not visible from the filter interface, so `isin` may not be available to use there...

As as aside, if you find you start needing a lot of Python manipulations on the records, another option is to use `fstpy` to select the records you need.  Then use something like `fstd2nc.Buffer.from_fstpy(df).to_netcdf("file.nc")` to write those records to netCDF.

**Comment by guziy** [comment]
this worked, pretty powerful: '[ el not in [59868832, 59968832] for el in ip1]`, I could combine it later with nomvar if needed, maybe they would want other variables on these levels... 

Thanks for the suggestion, writing a script is an option, but fstd2nc so far saves me from that))

**Comment by neishm** [comment]
A warning for filtering string variables (nomvar, typvar, grtyp, etiket): they are stored as arrays of _bytes_ padded to the expected size.  So, for instance, to select `TT` variable the hard way:
```
--filter 'nomvar==b"TT  "'
```

**Comment by guziy** [comment]
Ah yes, I bumped into that already, even submitted a mr, but is is still ignored...

This also works `~__import__(\"numpy\").isin(ip1, [59868832, 59968832])`

**Comment by neishm** [comment]
Ok, added the first two variants of numpy for filters.  The last one (`from numpy import *`) is crashing with the following error:
```
SyntaxError: import * only allowed at module level
```
so leaving that one out for now.

**Comment by guziy** [comment]
Thanks a lot, Michael: np is fine for me.

**Comment by neishm** [comment]
New version 0.20220204.1 has been installed on the EC / science networks.  This provides the updated `---filter` function.
