### ISSUE TITLE
Register fstd as an xarray backend

### ISSUE THREAD

**Issue by neishm** [neishm/fstd2nc#68]
See https://docs.xarray.dev/en/latest/internals/how-to-add-new-backend.html.

Should be possible to "register" this module for handling FST data, so that if `fstd2nc` is installed the following would work:
```python
import xarray as xr
ds = xr.open_dataset ("2023082900_024", engine="fstd", vars="TT,HU,P0")
```

**Comment by phil-blain** [comment]
Hi Mike, I just wanted to chime in to say that this is probably the single coolest thing about `fst2nc`. Cheers!
