### ISSUE TITLE
Problem with SIGINT signal (ctrl+c)

### ISSUE THREAD

**Issue by poitras-eccc** [neishm/fstd2nc#75]
I wrote a python scripts using at the same time the modules **fstd2nc** and **cdo**, When I tried to interrupt a job running in a terminal (ctrl+c) it is not working

Here is a simplified example reproducing the problem
```
import fstd2nc
from cdo import Cdo

cdo_tool = Cdo()

filein='/fs/site5/eccc/cmd/w/vpo018/dataSD/RDRS02p1PROD/data/hyb/1979/12/1979123112'

for i in range(0,100):
    print(i)
    ds = fstd2nc.Buffer(filein).to_xarray()

```
 
When I do ctrl+c, I received these kind of messages:
```
^Ccaught signal <cdo.Cdo object at 0x14ff4eef8820> 2 <frame at 0x14fe26c06d40, file '/fs/ssm/eccc/cmd/cmds/env/python/py39_2022.09.29_all/lib/python3.9/site-packages/xarray/core/variable.py', line 909, code attrs>
```

It looks like more a promblem with the **cdo** module than with the **fstd2nc** module. However, if I am not using both modules at the same time, ctrl+c works perfectly in both cases (so it seems there is a kind of interference problem between the modules)

- When using **fstd2nc** alone, ctrl+c works fine:
```
import fstd2nc
from cdo import Cdo

#cdo_tool = Cdo()

filein='/fs/site5/eccc/cmd/w/vpo018/dataSD/RDRS02p1PROD/data/hyb/1979/12/1979123112'

for i in range(0,100):
    print(i)
    ds = fstd2nc.Buffer(filein).to_xarray()

```

- When using **cdo** alone, ctrl+c works fine 

```
import fstd2nc
from cdo import Cdo

cdo_tool = Cdo()

filein='/fs/site5/eccc/cmd/w/vpo018/dataSD/RDRS02p1PROD/data/hyb/1979/12/1979123112'

for i in range(0,100000000000):
    print(i)
    #ds = fstd2nc.Buffer(filein).to_xarray()

```
 @neishm

**Comment by poitras-eccc** [comment]
@neishm

**Comment by neishm** [comment]
I'm trying to reproduce the issue on my end.  Could you provide some information on your environment, e.g. the output from
`python --version`
`cdo --version`
`fstd2nc --version`
`python -c "import cdo; print(cdo.__version__)"`

**Comment by neishm** [comment]
Ok, I can reproduce the problem with cdo-py version 1.5.7, but upgrading to cdo version 1.6.0 seems to resolve the issue.  Maybe they fixed it upstream?

**Comment by neishm** [comment]
I think it's this issue here: https://github.com/Try2Code/cdo-bindings/issues/43
Which indeed has been fixed in a more recent version of the cdo Python bindings.

**Comment by neishm** [comment]
This is also completely unrelated to your problem but I noticed in that sample file there are some accumulated quantities (PR,N0,O1).  There's an issue with processing those files with fstd2nc, where it only selects out one of the accumulation times.  It's been fixed in the development version, and a release version will be done soon.
(see: https://github.com/neishm/fstd2nc/commit/a7ed5fb703c4b9624cfdd7891743f7df6a929154)

**Comment by poitras-eccc** [comment]
Thank you very much for your quick reply!

At the end, the problem was only related with cdo. So, sorry to have bothered you with a problem non-related to fstd2nc, but thanks a lot for the explanation/solution.

Concerning your last comment on the accumulated quantities. In my case they are all 1-hour accumulation for different time step (dateo + ip3 is the starting time and datev = dateo + ip2 the ending hour). Since each field has a different datev, fstd2nc is handling the data correctly, but in any case thanks again to have been pro-active and try to prevent a possible forthcoming issue, it is really appreciated.

Vincent
