### ISSUE TITLE
Document that nomvar or etiket must be quoted when filtering

### ISSUE THREAD

**Issue by phil-blain** [neishm/fstd2nc#88]
Hi Mike,

I tried something like:
~~~python
ds_a = xr.open_dataset('/path/to/file', filter='etiket==ICETHICKNESS') 
~~~

and got `Exception: name 'ICETHICKNESS' is not defined`.

It works if the etiket is between quotes:
~~~python
ds_a = xr.open_dataset('/path/to/file', filter='etiket=="ICETHICKNESS"') 
~~~

but it is not immediately obvious from the documentation. Maybe a small mention of that would be enough when mentioning `filter`.

**Comment by neishm** [comment]
Yeah, that's a good idea.  Maybe at minimum a string example in `--help` and the Buffer docstring.  It's better than before, at least.  The syntax used to be `filter='etiket==b"ICETHICKNESS"'` or `filter='nomvar==b"P0  "'` before some extra string logic was added 😬 
Maybe some further logic could be added to auto-detect where quotes are probably needed (like bare sequences of capital letters  and numbers) and then try a quoted variation if the original filter is throwing a NameError.

**Comment by neishm** [comment]
On second thought I'll hold off on auto-adding quotes... while it would be convenient it would be tricky to implement.  I want to rely on Python to interpret the filter without needing a separate pre-parsing stage.
