### ISSUE TITLE
Support for in memory files

### ISSUE THREAD

**Issue by LandonRieger** [neishm/fstd2nc#93]
This tool has been great for reading `ccc` and `fstd` files so thank you for putting it together. One minor limitation I've ran into is that the file has to be on disc to be opened by `fstd2nc` when using it as an engine for `xarray`. Since we sometimes have the data in memory, writing to disc only to have it read again is a bit of an unnecessary step. For example:

```python
import xarray as xr
from io import BytesIO

# works great
xr.open_dataset('myfile.fst', engine='fstd')

# error : io.UnsupportedOperation: fileno
with open('myfile.fst', 'r') as f:
    buf = BytesIO(f.read())
xr.open_dataset(buf, engine='fstd')
```

I think this is due to a handful of locations where `np.fromfile` is used. Using `np.frombuffer` seems to get things moving, but I'm not sure if this is the right approach. If this is something you would like to see in the package I don't mind helping on the implementation side.

**Comment by neishm** [comment]
Thanks for the feedback!  That's certainly something that could be added.  There's few places where it's hard-coded to expect a filename.  For instance, under the hood the 'fstd' engine will create an `fstd2nc.Buffer` object, which expects to be initialized with a filename or list of files.  A special case could be added for when there's a raw byte stream, and modify any code that references the `_files` attribute.  Fortunately I don't think the format-specific code needs to be changed much, since the decoders are already given in-memory arrays of bytes.

I'm curious about the context of how these in-memory files are formed.  I thought librmn expected to create a file on disk, so this is something new to me.

**Comment by LandonRieger** [comment]
Great, one of my changes was in [`_expand_files`](https://github.com/neishm/fstd2nc/blob/805b74e2bfef92e581b66b3187b101b6bef4e9f8/fstd2nc/mixins/__init__.py#L241)` where I added
```python
elif isinstance(filename, BytesIO):
    return [(filename, filename)]
```
Which I think comes from `ExternInput`, one of the mixins for `Buffer`

Most of this is just experimentation on my part though, so there may be better ways to address the underlying issue. But generally, getting data into an `xarray` object is currently the slowest part of our processing chain for `fstd` files. Reading the data as a block from disc is surprisingly fast though (>10x faster than reading it into an `xarray` structure) so it's not purely a disc I/O problem. My thought was that getting this into memory fast (via a single read into `BytesIO` or similar) to avoid multiple reads of the disc by `fstd2nc` would help.

That said, I don't have a good understanding of how much processing is happening under the hood of `fstd2nc` so maybe reading the file is not the bottleneck at all.

**Comment by neishm** [comment]
Reading from a file on a memory-backed filesystem like `/tmp` would give some indication of how much bottleneck is disk I/O vs something else.  That *should* give similar timings to what would happen with in-memory BytesIO.

There could be a lot going on under the hood, depending on the dataset and options used.  Some things that come to mind:
- Using parameters `yin=True` or `yang=True` seems to slow it down a bit.
- Compression also seems to be a big factor for load time of the data.  For instance, data compressed as "f12" (nbits=12,datyp=134)  takes a lot less space on disk, but can take a lot longer to decode than uncompressed "E32" data (nbits=32,datyp=5).
- If there's a mixture of 3D model levels and near-surface diagnostic height, it may have to do two passes of the decoding to see if it can combine the diagnostic level as a model level "1.0" or if it needs to keep it separate.  This can be alleviated by using one of the parameters `ignore_diag_level=True`, `split_diag_level=True`, or `diag_as_model_level=True`.
- If only a handful of variable will be used, then pre-selecting them e.g. with `vars="VAR1,VAR2,VAR3"` would cut down on the amount of records that get processed

**Comment by LandonRieger** [comment]
Thanks, this is great to know. A colleague tested it on `/tmp` and didn't see too much improvement. So the in memory implementation probably isn't worth much time investment and I'll explore the other options you mentioned a bit more.

**Comment by neishm** [comment]
Ok, thanks for the update.  If in-memory file support becomes needed again, feel free to re-open.
