### ISSUE TITLE
Compression and speed

### ISSUE THREAD

**Issue by guziy** [neishm/fstd2nc#95]
Hi: 

this is not really an issue, it might be my inability to use the converter correctly.

I was trying to shrink the output netcdf files and still keep the timing low. I don't mind spending more computing resources, but it does not seem to help. 

I have a demonstration script here:

```
~olh001/data/ppp5/issues/fstd2nc/zlib-slow/test.sh
```

I tried running with and without `--zlib` .

````
# without --zlib
t=25s
output size=7.8G

# with --zlib
t=1m28s
output size=432M
````

I also tried playing with compression but it did not seem to change much for me. So basically `--zlib` solves the size problem but it takes like 10 times longer...

I am forced to tune this for the ensemble approach as for the 21 member I get  around 4TB of data from the 400Gb equivalent in the standard files.

Let me know if you have any suggestions, otherwise, I could try to avoid these temporary files by re-arranging tasks and using fstd2nc in my python scripts to read standard files....

**Comment by neishm** [comment]
Hi @guziy,

Yeah, compression on the netCDF side slows things down considerably.  The netCDF4-python library writes the data serially, and has to wait for each record to compress before it can be written (so not utilizing I/O to full potential).  

For that particular dataset, a small speedup is possible if you use the lowest level of compression possible (`--compression=1`).  This gives a slightly larger file (480M), but saves about 10% of the runtime.

There's also the `--turbo` option, which reads ahead and decompresses multiple FST records ahead of time so they're ready to send to netCDF immediately (so only bottleneck left is the re-compression on netCDF side).  This requires a lot more memory, though (I had to reserve 40GB to get it to work!) and needs 2 CPUs to utilize some parallel processing.

With both `--compression=1` and `--turbo`, it's getting closer to the uncompressed timings (but still takes 50% more time).  Any further speedups would require a different engine for writing to netCDF.

**Comment by neishm** [comment]
Doing the conversion from the Python interface (via xarray) seems to work a lot faster.  I'm guessing it's using a different engine for writing the netCDF file.  The following is giving similar timings to the uncompressed conversion from the command-line:
```python
import fstd2nc

root = "/home/olh001/data/ppp5/issues/fstd2nc/zlib-slow"
outdir = "."
inp = (root+"/2024101712_ice_eorca12_H096",
       root+"/2024101712_ice_eorca12_H192",
       root+"/2024101712_ice_eorca12_H288",
       root+"/2024101712_ice_eorca12_H384")

b = fstd2nc.Buffer(inp, vars='GL', exclude='depth,height,leadtime,reftime', ignore_etiket=True)
ds = b.to_xarray()

encoding = {var:{'zlib':True,'complevel':1} for var in ds.data_vars}

ds.to_netcdf(outdir+"/test_xarray.nc", encoding=encoding)
```
Output size is a bit larger (549M), but still a lot better than 7.8G.  Also requires 2 CPUs for parallelization (and enough memory to not crash).

**Comment by guziy** [comment]
Thanks a lot Michael!
