### ISSUE TITLE
xarray.open_mfdataset does not quite work

### ISSUE THREAD

**Issue by guziy** [neishm/fstd2nc#96]
Hi:
I was trying to use fstd2nc xarray interface, but I am  getting  an exception on exit from the `with` block with the following code:

```python
import xarray
with xarray.open_mfdataset("2024101712_wind_eorca12_H*") as ds:
    print(ds)
```

```
Traceback (most recent call last):
File "/fs/site5/eccc/cmd/e/olh001/issues/fstd2nc/multi-file-opn/test.py", line 5, in <module>
    with xarray.open_mfdataset("2024101712_wind_eorca12_H*") as ds:
  File "/fs/ssm/eccc/cmd/cmds/env/python/py310_2023.07.28_all/py310/lib/python3.10/site-packages/xarray/core/common.py", line 1392, in __exit__
    self.close()
  File "/fs/ssm/eccc/cmd/cmds/env/python/py310_2023.07.28_all/py310/lib/python3.10/site-packages/xarray/core/common.py", line 1169, in close
    self._close()
  File "/fs/ssm/eccc/cmd/cmds/env/python/py310_2023.07.28_all/py310/lib/python3.10/site-packages/xarray/backends/api.py", line 253, in _multi_fi$e_closer
    closer()
TypeError: 'NoneType' object is not callable
```

A self-contained `test.sh` script with the data can be found here:

```
/home/olh001/data/ppp5/issues/fstd2nc/multi-file-opn
```

Env info:
```
Python 3.10.12

In [2]: fstd2nc.__version__
Out[2]: '0.20240625.5'

In [3]: xarray.__version__
Out[3]: '2023.7.0'
```

**Comment by neishm** [comment]
Hi @guziy,

For loading FST files, the` open_dataset` method should be able to handle wildcards directly, e.g.
```python
import xarray
with xarray.open_dataset("2024101712_wind_eorca12_H*",engine="fstd") as ds:
    print(ds)
```
I can look into why it's failing for open_mfdataset (probably I'm returning None somewhere, or not implementing some method that it's expecting).  However, from my experience with netCDF files the open_mfdataset method can slow things down when there are a large number of files, so I would rather avoid using it if possible.

**Comment by neishm** [comment]
I think I have a fix (for whenever the next release is done).  However, would still recommend using open_dataset instead.

**Comment by guziy** [comment]
ah, nice, I've managed to make it work with xarray.concat, but if open_dataset supports lists of paths, that is great!
